export const ACTIONS = {
  VACATIONS: {
    GET_ALL_SUCCESS: "GET_ALL_SUCCESS",
    UPDATE: "UPDATE",
    DELETE_SUCCESS: "DELETE_SUCCESS",
    FOLLOW_SUCCESS: "FOLLOW_SUCCESS",
    UNFOLLOW_SUCCESS: "UNFOLLOW_SUCCESS",
    FILTER_FOLLOWED: "FILTER_FOLLOWED",
    SHOW_ONLY_FOLLOWED:"SHOW_ONLY_FOLLOWED",
    UNDO_SHOW_ONLY_FOLLOWED:"UNDO_SHOW_ONLY_FOLLOWED",
  },
  ADMIN: {
    GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
    EDIT: "EDIT",
    RESET_EDIT: "RESET_EDIT",
  },
  LOGIN: {
    SUCCESS: "SUCCESS"
  },
  LOGOUT: {
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS"
  },
  REGISTER: {
    REGISTER_SUCCESS: "REGISTER_SUCCESS"
  },
  ERROR: {
    TOGGLE: "TOGGLE",
  },
  LOADER: {
    SET_LOADER: "SET_LOADER",
    CLEAR_LOADER: "CLEAR_LOADER",
  }
};
